<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7986" started-at="2017-08-18T06:47:49Z" finished-at="2017-08-18T06:47:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7986" started-at="2017-08-18T06:47:49Z" finished-at="2017-08-18T06:47:57Z">
      <class name="sa.unitTestClass.LoginPageTest">
        <test-method status="PASS" signature="initPage()[pri:0, instance:sa.unitTestClass.LoginPageTest@3a82f6ef]" name="initPage" is-config="true" duration-ms="7815" started-at="2017-08-18T12:17:49Z" finished-at="2017-08-18T12:17:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initPage -->
        <test-method status="FAIL" signature="txtUsernameTest()[pri:0, instance:sa.unitTestClass.LoginPageTest@3a82f6ef]" name="txtUsernameTest" duration-ms="156" started-at="2017-08-18T12:17:57Z" finished-at="2017-08-18T12:17:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [sanjay3178] but found [sanjay31786]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [sanjay3178] but found [sanjay31786]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at sa.unitTestClass.LoginPageTest.txtUsernameTest(LoginPageTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- txtUsernameTest -->
      </class> <!-- sa.unitTestClass.LoginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
